### PR TITLE
Fix comments and add support for attached comments

### LINKED ISSUE #3: Add support for comments
Some estree parsers support comments.
Babel does too.
It would be nice to handle comments in estrees and add them to Babel trees too.

There are two ways to do comments.

- Comment attachment (fields on nodes, `leadingComments`, `trailingComments`, `innerComments`)
- Comment list (`comments` field on the program node with all comments)

Comment attachment is rather complex, espree recently removed it.

Here’s a breakdown of what I could find on astexplorer:

| Parser | Estree | Comment attachment | Comment list |
| - | - | - | - |
| `acorn` | yes | | with a couple lines of code |
| `@babel/eslint-parser` | yes | yes | yes |
| `@babel/parser` | | yes | yes |
| `espree` | yes | not anymore | yes |
| `esprima` | yes | yes | yes |
| `miriyah` | yes | | |
| `recast` | yes | sort of | |
| `traceur` | | | sort of |
| `recast` | yes | sort of | |
| `@typescript-eslint/parser` | yes | | yes |

It would be great if either attached comments could also make their way to Babel (transformed, because estree uses `Block` and `Line` types and Babel uses `BlockComment` and `LineComment`),
and it would be marvelous if an estree’s root `comments` array could also be attached to Babel nodes.

### PR DESCRIPTION
**Pull request by wooorm**
This change fixes semistandard estree comments: estree typically uses `Block`,
`Line`, whereas Babel uses `CommentBlock`, `CommentLine`.

This also adds support for attached comments: some estree parsers only support
top-level comments on `Program`, others support only attached comments (recast).
Babel supports both.
So, if either or both are provided, `estree-to-babel` to handles whichever is
given.

Closes GH-3.

### CODE REVIEW

File: lib/estree-to-babel.js [hunk 1]
```diff
@@ -53,3 +55,33 @@ module.exports = (node) => {
...
+        return;
+    
+    delete node.comments;
+    node.leadingComments = undefined;
+    node.trailingComments = undefined;
+    node.innerComments = undefined;
+    
+    for (const comment of comments) {
+        // Default to leading comment.
+        const type = comment.trailing ? 'trailingComments' : !comment.leading ? 'innerComments' : 'leadingComments';
```
Comment (coderaiser) [inline lib/estree-to-babel.js]: Let's create a function in the bottom of a file:

```js
 function getCommentType({trailing, leading}) {
     if (trailing)
        return 'trailingComments';
      
    if (comment.leading)
        return 'leadingComments';
               
    return 'innerComments' ;
}
```
And use it:

```suggestion       
        const type = getCommentType(comment);
```

Also let's move out function `setComment` into file `comments.js`.

File: lib/estree-to-babel.js [hunk 2]
```diff
@@ -53,3 +55,33 @@ module.exports = (node) => {
 function setObjectProperty(node) {
     node.type = 'ObjectProperty';
 }
+
+function setComments(node) {
```
Comment (coderaiser) [inline lib/estree-to-babel.js]:
```suggestion
function convertNodeComments(node) {
```

File: lib/estree-to-babel.js [hunk 3]
```diff
@@ -42,6 +42,8 @@ module.exports = (node) => {
         exit(path) {
             const {node} = path;
             
+            setComments(node);
```
Comment (coderaiser) [inline lib/estree-to-babel.js]:
```suggestion
            convertNodeComments(node);
```

File: lib/get-ast.js [hunk 4]
```diff
@@ -16,10 +16,19 @@ module.exports = (node) => {
...
         },
-        comments,
+        comments: comments.map(transformComment),
         tokens,
     };
     
     return ast;
 };
 
+function transformComment(comment) {
```
Comment (coderaiser) [inline lib/get-ast.js]: Let's move out this function into file `comments.js` with a name:

```suggestion
function convertProgramComments(comments) {
```

And there use `map`.

**Comment by coderaiser** [comment]
Thank you, this looks very good :). Could you please apply a couple changes to incapsulate comments transforming, so it can be accessible from one place: `comments.js`?

**Comment by wooorm** [comment]
I think this applies all your feedback!

I couldn’t easily visualize coverage. I’m assuming [this isn’t covered](https://github.com/coderaiser/estree-to-babel/pull/4/files#diff-5d6dc0246ff5c10022353e28e26c404ee8723708dd35f5d9e72122b00fb5bd51R45), which I still think is good to have

File: lib/comments.js [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+    if (type === 'Block')
+        return 'CommentBlock';
+    
+    // Assume an unknown type, or that it’s already a Babel type.
+    return type;
+}
+
+function getCommentGroup({trailing, leading}) {
+    if (trailing)
+        return 'trailingComments';
```
Comment (coderaiser) [inline lib/comments.js:49]: Would be great to cover with tests this line

File: lib/comments.js [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+    if (!comments)
+        return;
+    
+    delete node.comments;
+    node.leadingComments = undefined;
+    node.trailingComments = undefined;
+    node.innerComments = undefined;
+    
+    for (const comment of comments) {
+        // Default to leading comment.
```
Comment (coderaiser) [inline lib/comments.js]: We can drop this comment now

```suggestion
```

File: lib/comments.js [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+        node[group].push(comment);
+    }
+}
+
+function convertProgramComments(comments) {
+    return comments.map((comment) => {
+        comment.type = getCommentType(comment);
+        return comment;
+    });
+}
```
Comment (coderaiser) [inline lib/comments.js]:
```suggestion
function convertProgramComments(comments) {
    for (const comment of comments) {
        comment.type = getCommentType(comment);
    };
    
    return comments;
}
```

File: lib/comments.js [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+
+function getCommentType({type}) {
+    if (type === 'Line')
+        return 'CommentLine';
+    
+    if (type === 'Block')
+        return 'CommentBlock';
+    
+    // Assume an unknown type, or that it’s already a Babel type.
+    return type;
```
Comment (coderaiser) [inline lib/comments.js]:
```suggestion
```

I think we can remove this line if it can't be covered, it always can be improved in future, if there will be a need for this.

**Comment by coderaiser** [comment]
Thank you for applying changes, could you please add coverage for `trailingComments`, and I think we can drop `unknown type` for now (while it is unknown, and can't be covered with tests :)).

File: lib/comments.js [hunk 9]
```diff
@@ -0,0 +1,59 @@
+'use strict';
+
+exports.convertNodeComments = convertNodeComments;
+exports.convertProgramComments = convertProgramComments;
+
+function convertNodeComments(node) {
```
Comment (coderaiser) [inline lib/comments.js]:
```suggestion
module.exports.convertNodeComments = (node) => {
```

File: lib/comments.js [hunk 10]
```diff
@@ -0,0 +1,59 @@
+'use strict';
+
+exports.convertNodeComments = convertNodeComments;
+exports.convertProgramComments = convertProgramComments;
```
Comment (coderaiser) [inline lib/comments.js]:
```suggestion
```

File: lib/comments.js [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+            node[group] = [];
+        
+        delete comment.leading;
+        delete comment.trailing;
+        comment.type = getCommentType(comment);
+        node[group].push(comment);
+    }
+}
+
+function convertProgramComments(comments) {
```
Comment (coderaiser) [inline lib/comments.js]:
```suggestion
module.exports.convertProgramComments = (comments) => {
```

**Comment by wooorm** [comment]
This applies your feedback.

I do not think setting unknown nodes’ `type` fields to `CommentLine` or `CommentBlock` is great. Most of the code as it currently is leaves unknown nodes as they are and I think this should too. So I instead added a comment to ignore it in istanbul.

If you feel strongly about that, I can remove it though

**Comment by coderaiser** [comment]
All right, let's keep it :). Thanks a lot, landed in [v3.1.0](https://github.com/coderaiser/estree-to-babel/releases/tag/v3.1.0) 🎉

**Comment by wooorm** [comment]
Yay! Thanks! ✨
