### PR TITLE
fix: missing loc

### LINKED ISSUE #10: errors without loc
parsers such as https://github.com/meriyah/meriyah dont store the `loc` data in each node by default, but estree-to-babel assumes it exists and crashes

```js
const { parseScript } = require('meriyah');
const toBabel = require('estree-to-babel');
const fs = require('fs');

const src = fs.readFileSync('file.js', 'utf8');
const ast = toBabel(parseScript(src));
```
```
/tmp/test/node_modules/estree-to-babel/lib/traverse-object-expression.js:35
        start: key.loc.start,
                       ^

TypeError: Cannot read properties of undefined (reading 'start')
    at getObjectMethodLoc (/tmp/test/node_modules/estree-to-babel/lib/traverse-object-expression.js:35:24)
    at module.exports (/tmp/test/node_modules/estree-to-babel/lib/traverse-object-expression.js:25:22)
    at exit (/tmp/test/node_modules/estree-to-babel/lib/estree-to-babel.js:89:24)
    at NodePath._call (/tmp/test/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/tmp/test/node_modules/@babel/traverse/lib/path/context.js:32:14)
    at NodePath.visit (/tmp/test/node_modules/@babel/traverse/lib/path/context.js:90:8)
    at TraversalContext.visitQueue (/tmp/test/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/tmp/test/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/tmp/test/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/tmp/test/node_modules/@babel/traverse/lib/traverse-node.js:18:17)

Node.js v18.12.0
```

https://github.com/coderaiser/estree-to-babel/blob/a99f4ea740203d5749285de5ba383071e65a98d8/lib/traverse-object-expression.js#L35

### PR DESCRIPTION
**Pull request by j4k0xb**
fixes #10 and also add `loc` to all other nodes where it was missing

### CODE REVIEW

File: lib/convert-import-to-call.js [hunk 1]
```diff
@@ -2,19 +2,29 @@
...
 const setLiteral = require('./set-literal');
 
 module.exports = (path) => {
-    const {source} = path.node;
+    const {loc, source} = path.node;
     
     setLiteral(source);
     
-    const callNode = CallExpression(Identifier('import'), [
+    const calleeNode = Import();
```
Comment (coderaiser) [inline lib/convert-import-to-call.js]: This is a very good point!

File: test/estree-to-babel.js [hunk 2]
```diff
@@ -370,7 +387,7 @@ test('estree-to-babel: parse: InterfaceHeritage', (t) => {
 });
 
 test('estree-to-babel: parse: TSAbstractMethodDefinition', (t) => {
-    const ast = tsEstree.parse(fixture.js.tsAbstractMethodDefinition);
+    const ast = tsParse(fixture.js.tsAbstractMethodDefinition);
```
Comment (coderaiser) [inline test/estree-to-babel.js]: Why so many tests changed? Maybe let's add one new test case with maryah parser instead?

File: lib/convert-import-to-call.js [hunk 3]
```diff
@@ -1,11 +1,10 @@
 'use strict';
 
 const {CallExpression, Import} = require('@babel/types');
-
 const setLiteral = require('./set-literal');
 
 module.exports = (path) => {
-    const {source} = path.node;
+    const {loc, source} = path.node;
```
Comment (coderaiser) [inline lib/convert-import-to-call.js]:
```suggestion
    const {source} = path.node;
```

File: lib/convert-import-to-call.js (hunk 1 above)
Comment (coderaiser) [reply lib/convert-import-to-call.js]: Could you please tell me a little bit more about `loc` in `callee` why do you need it?

Comment (j4k0xb) [reply lib/convert-import-to-call.js]: I don't personally need it, just looked through the fixtures and made it look like the babel ast:
image
only merging the bug fix without the added `loc` is also fine if you want

Comment (coderaiser) [reply lib/convert-import-to-call.js]: OK, I see, all this have sense. Could you please add one test with `maryiah` parser and get back loc calculation for `Imports`.
